#ifndef METHOD_H
#define METHOD_H

#include "include/Global.h"
#include <string>
using namespace std;

#define METHOD_DECLARE(name)		static string name
#define METHOD_DEFINE(name, value)	string Method::name = value

class Method
{
public:
    METHOD_DECLARE(ADMIN_GET_ALLOCATION);

    METHOD_DECLARE(FRIENDS_ARE_FRIENDS);
    METHOD_DECLARE(FRIENDS_GET);
    METHOD_DECLARE(FRIENDS_GET_FRIENDS);
    METHOD_DECLARE(FRIENDS_GET_APP_FRIENDS);

    METHOD_DECLARE(INVITATIONS_CREATE_LINK);
    METHOD_DECLARE(INVITATIONS_GET_INFO);

    METHOD_DECLARE(NOTIFICATIONS_SEND);
    METHOD_DECLARE(NOTIFICATIONS_SEND_EMAIL);

    METHOD_DECLARE(PAGES_IS_FAN);

    METHOD_DECLARE(PAY_IS_COMPLETED);
    METHOD_DECLARE(PAY_REG_ORDER);
    METHOD_DECLARE(PAY_IS_COMPLETED_4_TEST);
    METHOD_DECLARE(PAY_REG_ORDER_4_TEST);

	METHOD_DECLARE(USERS_GET_LOGGED_IN_USER);
    METHOD_DECLARE(USERS_GET_INFO);
    METHOD_DECLARE(USERS_HAS_APP_PERMISSION);
    METHOD_DECLARE(USERS_IS_APP_USER);

    METHOD_DECLARE(STATUS_GETS);
    METHOD_DECLARE(STATUS_SET);
    METHOD_DECLARE(STATUS_GET);
    METHOD_DECLARE(STATUS_GET_COMMENT);

    METHOD_DECLARE(PHOTOS_CREATE_ALBUM);
    METHOD_DECLARE(PHOTOS_GET_ALBUMS);
    METHOD_DECLARE(PHOTOS_UPLOAD);
    METHOD_DECLARE(PHOTOS_GET);

private:
	Method() {}
};

#endif	//METHOD_H
